### ISSUE TITLE
Full Stack example: Cannot read property ‘match’ of undefined

### ISSUE THREAD

**Issue by cyr-l** [ory/examples-archive#20]
Full Stack example is giving me an error, right off the bat (which is _not_ cool ^^)

### Steps to reproduce:

- `make start-full-stack`
- `hydra token user --client-id example-auth-code --client-secret secret --endpoint http://localhost:4444 --port 5555`
- Browse `http://localhost:5555` and click the Authorize link

### Stack trace: 

```
TypeError: Cannot read property ‘match’ of undefined
    at normalize (/usr/src/app/node_modules/url-join/lib/url-join.js:11:21)
    at /usr/src/app/node_modules/url-join/lib/url-join.js:70:12
    at get (/usr/src/app/services/hydra.js:8:16)
    at Object.getLoginRequest (/usr/src/app/services/hydra.js:49:12)
    at /usr/src/app/routes/login.js:17:9
    at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/src/app/node_modules/express/lib/router/route.js:131:13)
    at csrf (/usr/src/app/node_modules/csurf/index.js:117:5)
    at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/src/app/node_modules/express/lib/router/route.js:131:13)
```

**Comment by cyr-l** [comment]
Oh. The error probably occurs because `HYDRA_URL` is not set in the Login/Consent container.

**Comment by aeneasr** [comment]
I re-relased the v1.0.0-beta.9 release of the login/consent app. It will take a bit to build (~10-20 minutes) but once it's up you should do `docker pull oryd/hydra-consent-app-express:v1.0.0-beta.9` to ensure that you have the proper docker image and then run `make reset-full-stack`. That should do the trick!

**Comment by cyr-l** [comment]
Ok, cool. Thank you.

Don't worry, I could keep on working on it by updating the `docker-compose` file.
