### ISSUE TITLE
Secure backend with ORY Oathkeeper is not working 

### ISSUE THREAD

**Issue by cyr-l** [ory/examples-archive#23]
When attempting to access `/articles/secure-backend-with-ory-oathkeeper` with a valid access token, the following error occurs:

```
<!DOCTYPE html>
<html>
    <head>
        <title></title>
    </head>
    <body>
        <h1>invalid signature</h1>
        <h2>401</h2>
        <pre>UnauthorizedError: invalid signature
    at /usr/src/app/node_modules/express-jwt/lib/index.js:102:22
    at Object.module.exports [as verify] (/usr/src/app/node_modules/jsonwebtoken/verify.js:102:12)
    at verifyToken (/usr/src/app/node_modules/express-jwt/lib/index.js:100:13)
    at fn (/usr/src/app/node_modules/async/lib/async.js:746:34)
    at /usr/src/app/node_modules/async/lib/async.js:1213:16
    at /usr/src/app/node_modules/async/lib/async.js:166:37
    at /usr/src/app/node_modules/async/lib/async.js:706:43
    at /usr/src/app/node_modules/async/lib/async.js:167:37
    at Immediate.&lt;anonymous&gt; (/usr/src/app/node_modules/async/lib/async.js:1206:34)
    at runCallback (timers.js:696:18)</pre>
    </body>
</html>
```

![screen-shot](https://user-images.githubusercontent.com/215009/45148720-34127300-b1c8-11e8-9902-414d15974d3e.png)

**Comment by aeneasr** [comment]
This should now work at all times as there are now integration/e2e tests for this as well!
